export const SUBMIT_CORRECT_RESPONSE = 'SUBMIT_CORRECT_RESPONSE';
export const NEXT_QUESTION = 'NEXT_QUESTION';
export const PREVIOUS_QUESTION = 'PREVIOUS_QUESTION';
export const USE_HINT = 'USE_HINT';
